version: '3.8'

networks:
    rr-example:

services:
    php:
        image: rr-example
        build:
            context: .
        command: "rr serve -c rr.yaml -p"
        environment:
            - NUM_POLLERS=128
            - NUM_WORKERS=64
        networks:
            - rr-example

    rabbitmq:
        image: rabbitmq:3.11-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - rr-example
